spring:
  application:
    name: job-portal-ai-service

  config:
    import: configserver:http://localhost:8888


gemini:
  api:
    key: AQ.Ab8RN6IdkPmNhR2tXzpuApf9ax7MaV4pK_4ff-GqNqatPjJT3g
    model: gemini-3.5-flash-lite
    max-output-tokens: 2048
    temperature: 0.7